version: '3.6'

services:
    cwod-example-docker:
        image: cwod-example-docker:latest
        build:
            context: ..
            dockerfile: ./example_docker/Dockerfile
        entrypoint:
            - python
        environment:
            BROKER: redis://redis:6379/0
            BACKEND: redis://redis:6379/0
        depends_on:
            - redis
    agent:
        image: cwod-example-docker:latest
        entrypoint:
            - python
            - -m
            - example
        environment:
            BROKER: redis://redis:6379/0
            BACKEND: redis://redis:6379/0
        depends_on:
            - redis
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    redis:
        image: redis:latest
        ports:
            - 6379:6379

networks:
    default:
        name: cwod-example-docker
